language: node_js

node_js:
  - "stable"
  
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --no-sandbox --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - npm run test
after_success: 'npm run coveralls'