language: node_js

node_js:
  - "stable"
  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
before_install:
  - google-chrome-stable --headless --no-sandbox

script:
  - npm run test
  - npm run prod

