language: node_js

node_js:
  - "stable"

cache: yarn

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --no-sandbox --disable-gpu --remote-debugging-port=9222 http://localhost &
  
script:
  - npm run test
  - npm run report-coverage